// lib/roleAccessConfig.ts

export type Role = "ADMIN" | "BACKEND" | "RM" | "MST" | "ACCOUNTS";

// Define the role-based access configuration for navigation items
export const navRoleAccess: Record<Role, string[]> = {
  ADMIN: [
    "Dashboard",
    "Kanban Board",
    "Clients",
    "Agents",
    "Finances",
    "Quotations",
    "Expenses",
    "Rate Card",
    "Calls",
    "Email Templates",
    "Settings",
  ],
  BACKEND: [
    "Dashboard",
    "Kanban Board",
    "Clients",
    "Agents",
    "Quotations",
    "Expenses",
    "Rate Card",
    "Calls",
    "Email Templates",
    "Settings",
  ],
  RM: [
    "Dashboard",
    "Kanban Board",
    "Clients",
    "Agents",
    "Quotations",
    "Expenses",
    "Rate Card",
    "Calls",
    "Email Templates",
    "Settings",
  ],
  MST: [
    "Dashboard",
    "Kanban Board",
    "Clients",
    "Agents",
    "Quotations",
    "Expenses",
    "Rate Card",
    "Calls",
    "Email Templates",
    "Settings",
  ],
  ACCOUNTS: [
    "Dashboard",
    "Kanban Board",
    "Clients",
    "Agents",
    "Quotations",
    "Expenses",
    "Rate Card",
    "Calls",
    "Email Templates",
    "Settings",
  ],
};

// Define the role-based access configuration for paths
export const pathRoleAccess: Record<Role, string[]> = {
  ADMIN: [
    "/dashboard",
    "/dashboard/kanban",
    "/dashboard/clients",
    "/dashboard/agents",
    "/dashboard/quotations",
    "/dashboard/expenses",
    "/dashboard/rate-card",
    "/dashboard/calls",
    "/dashboard/email-template",
    "/dashboard/settings",
    "/admin",
  ],
  BACKEND: [
    "/dashboard",
    "/dashboard/kanban",
    "/dashboard/clients",
    "/dashboard/agents",
    "/dashboard/quotations",
    "/dashboard/expenses",
    "/dashboard/rate-card",
    "/dashboard/calls",
    "/dashboard/email-template",
    "/dashboard/settings",
    "/admin",
  ],
  RM: [
    "/dashboard",
    "/dashboard/kanban",
    "/dashboard/clients",
    "/dashboard/agents",
    "/dashboard/quotations",
    "/dashboard/expenses",
    "/dashboard/rate-card",
    "/dashboard/calls",
    "/dashboard/email-template",
    "/dashboard/settings",
    "/admin",
  ],
  MST: [
    "/dashboard",
    "/dashboard/kanban",
    "/dashboard/clients",
    "/dashboard/agents",
    "/dashboard/quotations",
    "/dashboard/expenses",
    "/dashboard/rate-card",
    "/dashboard/calls",
    "/dashboard/email-template",
    "/dashboard/settings",
    "/admin",
  ],
  ACCOUNTS: [
    "/dashboard",
    "/dashboard/kanban",
    "/dashboard/clients",
    "/dashboard/agents",
    "/dashboard/quotations",
    "/dashboard/expenses",
    "/dashboard/rate-card",
    "/dashboard/calls",
    "/dashboard/email-template",
    "/dashboard/settings",
    "/admin",
  ],
};
